# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post_data',
            new_name='PostData',
        ),
    ]
