# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0004_auto_20160809_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='college_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postdata',
            name='group',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postdata',
            name='sex',
            field=models.CharField(max_length=255),
        ),
    ]
