# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0006_auto_20160809_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdata',
            old_name='date_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='postdata',
            old_name='college_name',
            new_name='forum_alias',
        ),
        migrations.RenameField(
            model_name='postdata',
            old_name='forumAlias',
            new_name='forum_name',
        ),
        migrations.RenameField(
            model_name='postdata',
            old_name='forumName',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='postdata',
            old_name='sex',
            new_name='school_name',
        ),
    ]
