# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0008_postdata_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParseError',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
    ]
