# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0009_parseerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdata',
            name='status',
            field=models.CharField(default='online', max_length=255),
            preserve_default=False,
        ),
    ]
